# Generated by Django 3.1 on 2020-08-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='End_Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='Start_Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
