# Generated by Django 3.1 on 2020-08-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200807_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='End_Time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='activityperiod',
            old_name='Start_Time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Full_Name',
            new_name='real_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Time_Zone',
            new_name='tz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Employee_Id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
